name: inventory-management

services:
  mongo:
    image: mongo:7
    container_name: inventory_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inventory_management
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: inventory_api
    restart: unless-stopped
    ports:
      - '7700:7700'
    command: ["pnpm", "start:dev"]   # ✅ fixed, removed "mongo:27017"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      MONGODB_URI_DEV: mongodb://mongo:27017/inventory_management
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7
    container_name: inventory_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  mongo_data:
  redis_data:
